version: '3.5'

services:
  backend:
    container_name: top-rock-abums-be
    image: top-rock-albums-be
    build: ./top-rock-albums-be/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    build: ./postgres/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    
volumes:
    postgres:
