version: '3.5'

services:
  postgres:
    build: ./postgres/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
    postgres:
